apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: attestationpolicies.frayer.org
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: frayer.org
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                trustedAttestationAuthority:
                  type: string
                requiredAttestations:
                  type: object
                  properties:
                    allOf:
                      imagePatternMatch:
                        type: array
                        items:
                          type: string
                    oneOf:
                      imagePatternMatch:
                        type: array
                        items:
                          type: string
                imagePatternMatch:
                  type: array
                  items:
                    type: string
                imagePatternIgnore:
                  type: array
                  items:
                    type: string
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: attestationpolicies
    # singular name to be used as an alias on the CLI and for display
    singular: attestationpolicy
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: AttestationPolicy
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - attpolicy
