name: opa test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download Open Policy Agent CLI
        run: |
          curl -L -o /usr/local/bin/opa https://openpolicyagent.org/downloads/v0.31.0/opa_linux_amd64_static
          chmod 755 /usr/local/bin/opa

      - name: Execute OPA tests
        run: |
          opa test -v ./policy
